language: c
env:
  global:
    - LUAROCKS_BASE=luarocks-2.2.1
    - LUA_VER=5.2
    - LUA_SFX=5.2
    - LUA_INCDIR=/usr/include/lua5.2
    - RIEMANN_VERSION=0.2.9
    - RIEMANN_C_CLIENT_VERSION=1.4.0
before_install:
  - wget http://aphyr.com/riemann/riemann_${RIEMANN_VERSION}_all.deb
  - sudo dpkg -i riemann*deb
  - sudo service riemann start
  - wget https://github.com/algernon/riemann-c-client/releases/download/riemann-c-client-${RIEMANN_C_CLIENT_VERSION}/riemann-c-client-${RIEMANN_C_CLIENT_VERSION}.tar.xz
  - tar xJf riemann-c-client-${RIEMANN_C_CLIENT_VERSION}.tar.xz
  - wget http://luarocks.org/releases/${LUAROCKS_BASE}.tar.gz
  - tar zxvpf ${LUAROCKS_BASE}.tar.gz
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lua${LUA_VER} liblua${LUA_VER}-dev protobuf-c-compiler libprotobuf-c0-dev
  - cd riemann-c-client-${RIEMANN_C_CLIENT_VERSION} && ./configure && make && sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
  - cd $LUAROCKS_BASE
  - ./configure --lua-version=$LUA_VER --lua-suffix=$LUA_SFX
  - make build && sudo make install
  - cd $TRAVIS_BUILD_DIR
  - sudo luarocks install busted
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules CFLAGS="-Wall -Wextra -O3 -g"
  - make
  - make check VERBOSE=1
compiler:
  - gcc
  - clang
